services:
  backend:
    build:
      context: ./backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - area-network

  frontend:
    build:
      context: ./frontend  # Update the context to point to the correct directory
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:8000/api
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - area-network

networks:
  area-network: {}